export const NOTE_REPOSITORY = 'NOTE_REPOSITORY';
export const PROJECT_REPOSITORY = 'PROJECT_REPOSITORY';
export const CLIENT_CHARGE_REPOSITORY = 'CLIENT_CHARGE_REPOSITORY';
export const PARTNER_PAYMENT_REPOSITORY = 'PARTNER_PAYMENT_REPOSITORY';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const PARTNER_REPOSITORY = 'PARTNER_REPOSITORY';
export const LOG_REPOSITORY = 'LOG_REPOSITORY'; 